name: 'ICMS Content Hub Recipe'
description: 'A content type and view to help you manage events.'
type: 'Site'

install:
  # Core
  - node
  - user
  - views
  # Contrib
  - blokkli_starterkit
  - graphql_core_schema
  - tagify_user_list
  - conditional_fields

config:
  actions:
  # GraphQL Core Schema
    graphql.graphql_servers.graphql:
      simple_config_update:
        schema_configuration.core_composable.fields.paragraph.field_icms_topics: field_icms_topics
        schema_configuration.core_composable.fields.node.field_icms_contenthub_duration: field_icms_contenthub_duration
        schema_configuration.core_composable.bundles.node.icms_contenthub_article:
          enabled: true
        schema_configuration.core_composable.fields.paragraph.field_icms_listing_type: field_icms_listing_type
        schema_configuration.core_composable.bundles.paragraph.icms_layout_contenthub:
          enabled: true
        schema_configuration.core_composable.fields.user.user_picture: user_picture
  # Enable the Content Hub Paragraph type on all node types
    field.field.node.*.field_icms_paragraphs:
      simple_config_update:
        settings.handler_settings.target_bundles.icms_layout_contenthub: icms_layout_contenthub
        settings.handler_settings.target_bundles_drag_drop.icms_layout_contenthub.enabled: true
    paragraphs_blokkli.settings:
      'simpleConfigArray:append':
        property: enabled_types.node
        values: [icms_contenthub_article]
