name: 'Content Hub Artikel'
description: 'Artikel-Format für den Content Hub. Wird verwendet, um themenbezogene Beiträge mit benutzerdefinierten Veröffentlichungsdaten, geschätzter Lesezeit, Taxonomie-Tags und ICMS-Layout-Komponenten zu erstellen. Unterstützt mehrsprachige Inhalte und strukturierte Teaser.'
help: ''
