name: 'Content Hub Artikel'
description: 'Verwende <em>Content Hub Articles</em>, um themenbezogene Beiträge mit individuellem Veröffentlichungsdatum, Lesezeit, Taxonomie-Tags und ICMS-Layout-Komponenten zu erstellen.'
third_party_settings:
  node_title_help_text:
    title_help: 'Haupttitel der Seite. Wird für Meta-Daten, Menüeintrag und die Anzeige im Backend verwendet, sofern nicht überschrieben.'
help: ''
